### ISSUE TITLE
希望能发布一个React Hooks版本的

### ISSUE THREAD

**Issue by macroswang** [hsl947/react-antd-multi-tabs-admin#1]

**Comment by hsl947** [comment]
@macroswang  现在就是啊，大部分都有用hooks了，只是还混杂几个Class组件，如果有意愿，我会抽出时间全部改成 hooks 😁

**Comment by hsl947** [comment]
@macroswang 所有组件都已经改成 hooks 😉，欢迎提 bug 或优化
