### ISSUE TITLE
antd升级到4.7.0之后，主题颜色为亮白的时候，tab的颜色有点问题

### ISSUE THREAD

**Issue by xiashulin** [hsl947/react-antd-multi-tabs-admin#10]
![image](https://user-images.githubusercontent.com/11418033/106221840-53871c00-6219-11eb-9613-6010f3bf427d.png)

**Comment by hsl947** [comment]
@xiashulin 经排查，高版本antd Tabs 的 dom结构和样式类名都改动了..😭 
 已做兼容，谢谢反馈！🤝
