### ISSUE TITLE
好像并没有实现关于 /user/:id 这种动态路由匹配

### ISSUE THREAD

**Issue by SugarTiger** [hsl947/react-antd-multi-tabs-admin#11]
## Feature request（新功能建议）

好像并没有实现关于 /user/:id 这种动态路由匹配

**Comment by hsl947** [comment]
@SugarTiger 是的，因为路由权限控制是根据路由地址精准控制的，动态路由id的话，会出现一些问题。
建议使用 query形式的参数 `?query=xxx` 😉。
我会尝试优化看看，前提是不需要控制权限的情况下增加此功能。
谢谢支持！🤝
