### ISSUE TITLE
建议文档写详细点

### ISSUE THREAD

**Issue by xu-Aurora** [hsl947/react-antd-multi-tabs-admin#12]
## Feature request（新功能建议）

比如路由权限的思路可以介绍的详细点，纯开代码有点累，毕竟不知道你的思路的。假如文档把思路写出来了，然后再跟着代码看逻辑的话要好点

**Comment by xu-Aurora** [comment]
还有个问题好奇怪，在当前项目的页面，我鼠标右键怎么没有效果？想审查元素都不可以，必须要按F12才可以。但在别的页面鼠标右键是可以的

**Comment by hsl947** [comment]
@xu-Aurora 好的，这个建议挺实在的，接下来会列入优化清单😃。
鼠标右键无法使用是因为禁用了，跟tab上自定义的右键菜单才不会冲突。
多谢支持哈，持续更新💪

**Comment by xu-Aurora** [comment]
我还发现了一个问题，不知道算不算bug。打个比方，a和b页面在tab标签那里都存在了，a和b页面的接口数据是关联的，我在a页面操作接口了，但我从tab那里点击进入b页面，b页面没有重新从接口获取，所以b页面获取到的就不是最新数据了

**Comment by xu-Aurora** [comment]
我还发现了一个问题，不知道算不算bug。打个比方，a和b页面在tab标签那里都存在了，a和b页面的接口数据是关联的，我在a页面操作接口了，但我从tab那里点击进入b页面，b页面没有重新从接口获取，所以b页面获取到的就不是最新数据了

**Comment by hsl947** [comment]
@xu-Aurora 这个我懂，并不是bug。多页签的一个基本原则，就是切换tab时，不能每次都请求接口，否则就失去多页签共存的意义了。要刷新的话，可以tab页签上右键【刷新当前tab】。

**Comment by hsl947** [comment]
@xu-Aurora 举个栗子哦。比如有个【列表页】和【编辑表单页】，当我在编辑表单时，如果每次切换tab回来都刷新数据，那么已编辑内容就会被还原为初始，你细品😅。这个防刷新是我刻意控制的。

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/118206097-5b02c600-b494-11eb-9120-01f8cb8d2a53.png)
我的事mac，项目每次启动都会弹出这个，百度上也没有找到什么办法解决，虽然选择y就可以了

**Comment by hsl947** [comment]
@xu-Aurora 因为mac默认不开启1024以上的端口权限，可以修改配置文件或做接口转发。
[参考链接](https://blog.csdn.net/qq_31319235/article/details/115668530)

**Comment by xu-Aurora** [comment]
你的权限控制我有发现了一个不足，我随便输入一个地址，你直接就跳转403了，应该只有跳转路由中存在但没有权限的才403吧。应该要弄个404页面吧，这样更友好点，个人觉得

**Comment by xu-Aurora** [comment]
> @xu-Aurora 因为mac默认不开启1024以上的端口权限，可以修改配置文件或做接口转发。
> [参考链接](https://blog.csdn.net/qq_31319235/article/details/115668530)

那我可以换端口啊，这个配置端口要怎么弄？感觉和一般的webpack不一样啊 。。。。

**Comment by hsl947** [comment]
@xu-Aurora 加微信聊吧，这边回复不即时，我的 `hsl947123`
