### ISSUE TITLE
右键菜单功能失效

### ISSUE THREAD

**Issue by 01super** [hsl947/react-antd-multi-tabs-admin#16]
#### Steps to reproduce（问题复现步骤）
鼠标右键菜单事件被阻止，无法弹出原生菜单

**Comment by 01super** [comment]
找到你代码中有一下代码  
onContextMenu={(e) => e.preventDefault()}  
请问大佬是为何原因禁用该处事件？

**Comment by hsl947** [comment]
@hsl947 因为tab标签上有自定义右键菜单，不禁用原生的会同时显示两个菜单

**Comment by 01super** [comment]
> @hsl947 因为tab标签上有自定义右键菜单，不禁用原生的会同时显示两个菜单，有需要的话自行注释掉吧

另外还有一个地方也有阻止事件，导致其他地方的也无法弹出菜单。

**Comment by hsl947** [comment]
@YingHuaLiu 这个你自行去掉吧😁
