### ISSUE TITLE
遇到一个问题

### ISSUE THREAD

**Issue by 1260323835** [hsl947/react-antd-multi-tabs-admin#17]
大佬，您好，我在学习您 的项目的时候遇到了一个问题，在使用redux的时候，我尝试使用react hooks来操作redux，我在使用useSelector来订阅store的时候，我无法获取到state里的值
![image](https://user-images.githubusercontent.com/64878070/131096028-728c4843-26e6-4149-94e2-4d307341a73f.png)
我在控制台中获取到的值是
![image](https://user-images.githubusercontent.com/64878070/131096209-75279c81-cbc7-47ec-9014-2a32ffd559ac.png)
这里可以看到，在redux-logger，state里是存在该值的，请问一下这个是啥问题？

**Comment by hsl947** [comment]
@1260323835 微信 15980763390，欢迎互相学习
