### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by wkylin** [hsl947/react-antd-multi-tabs-admin#19]
## Bug report（问题描述）
```
error Couldn't find package "immutable@*" required by "draft-js-multidecorators@^1.0.0" on the "npm" registry.
```

#### Other relevant information（格外信息）
- Your OS:
- Your broswer version:

**Comment by hsl947** [comment]
@wkylin 我这边重新用npm安装依赖了，亲测没问题。可能是你的node或npm版本问题，或者是你npm库用的不是官方库（比如淘宝源），请检查一下。
