### ISSUE TITLE
请问分页器无效是什么原因呢

### ISSUE THREAD

**Issue by easy4yb** [hsl947/react-antd-multi-tabs-admin#21]
# 分页器无效

无论选20条/页还是50条/页，列表都只能显示10条/页。

**Comment by easy4yb** [comment]
![image](https://user-images.githubusercontent.com/77675944/144036354-3e4d5f35-55f3-4eec-b51d-9d0670ae0bab.png)

**Comment by hsl947** [comment]
@easy4yb demo里的数据是第三方模拟数据，分页大小字段可能无效，实际开发中请以后端字段为准。
