### ISSUE TITLE
可否做些依赖升级？！

### ISSUE THREAD

**Issue by wkylin** [hsl947/react-antd-multi-tabs-admin#22]
## Feature request（新功能建议）
拷贝项目到本地后安装依赖，本地项目运行不了😂

依据提示在.env文件中新增了SKIP_PREFLIGHT_CHECK=true 方才启动项目😊

报错提示：

![企业微信截图_20211213203437](https://user-images.githubusercontent.com/1208330/145815719-8849e454-6dd3-4f71-ac31-ebb95df18bfa.png)

**Comment by theCword** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
