### ISSUE TITLE
换肤

### ISSUE THREAD

**Issue by gujiwuqing** [hsl947/react-antd-multi-tabs-admin#23]
## Feature request（新功能建议）

关于换肤的话 antd现在是有这个功能了 你可以看一下文档
https://ant.design/docs/react/customize-theme-variable-cn

**Comment by hsl947** [comment]
@gujiwuqing 谢谢支持，我先学习一下大厂的思路

**Comment by gujiwuqing** [comment]
> @gujiwuqing 谢谢支持，我先学习一下大厂的思路

互相学习 我用了这个 很简单的
