### ISSUE TITLE
我把所有的包都更新后。发现customize-cra使用有问题，亮白主题皮肤不正常了。

### ISSUE THREAD

**Issue by macroswang** [hsl947/react-antd-multi-tabs-admin#3]
你好兄弟
我把所有的包都更新后。发现customize-cra使用有问题，亮白主题皮肤不正常了。
还有就是你系统管理这块，可不可以把用户、角色、权限、菜单功能都完善一下呢？

**Comment by hsl947** [comment]
@macroswang 主题切换不正常，有报什么错吗？

**Comment by macroswang** [comment]
没有。应该是CSS样式没起作用了。CSS是我的弱项，，调了1个小时都没有解决:(
你可以试试就知道了

**Comment by hsl947** [comment]
@macroswang 我这个只是个简单的脚手架模板😅，满足基本功能。你的指的完善 【用户 角色 权限 菜单】具体是做啥，因为里面已经集成菜单、页面权限控制，不太明白你说的

**Comment by hsl947** [comment]
@macroswang 有没有线上预览地址，我帮你看看问题

**Comment by macroswang** [comment]
customize-cra更新到1.0.0后我修改成了这样
addLessLoader({
    lessOptions: {
      modifyVars: {
        'hack': `true;@import "${require.resolve('antd/lib/style/color/colorPalette.less')}";`,
        ...darkThemeVars,
        '@primary-color': '#6e41ff',
      },
      javascriptEnabled: true,
      localIdentName: '[local]--[hash:base64:5]',
    },
  })

**Comment by hsl947** [comment]
@macroswang 可能是不兼容，建议是按照模板里的版本号来按照依赖，不需要更新，最新的不一定最好😅
你把 node_module 删掉重装吧，然后用 yarn install

**Comment by macroswang** [comment]
只有这样了。谢谢

**Comment by macroswang** [comment]
解决了。是因为antd升级的问题造成的！

**Comment by qld-cf** [comment]
> 解决了。是因为antd升级的问题造成的！

@macroswang 怎么解决的呢 同样问题

**Comment by hsl947** [comment]
@qld-cf 建议你把antd的版本号固定 4.2.0，再重新安装依赖
`"antd": "^4.2.0"` -> `"antd": "4.2.0"`
