### ISSUE TITLE
关闭左侧导航栏后文字消失

### ISSUE THREAD

**Issue by Haiwar** [hsl947/react-antd-multi-tabs-admin#40]
#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/35055270/163755137-96d1f622-3cdf-4ab2-847b-01ad9799a6ba.png)

#### Other relevant information（格外信息）
- Your OS:
- Your broswer version:

**Comment by hsl947** [comment]
@tearf001 麻烦帮忙检查一下问题，谢谢

**Comment by hsl947** [comment]
@Haiwar 如果你验证问题已修复，请关闭此 issue 让我知道。😉

**Comment by Haiwar** [comment]
> @Haiwar 如果你验证问题已修复，请关闭此 issue 让我知道。😉
