### ISSUE TITLE
这样做多tab功能，当页面元素多了是否会卡顿

### ISSUE THREAD

**Issue by ZmSama** [hsl947/react-antd-multi-tabs-admin#43]

**Comment by hsl947** [comment]
@ZmSama 感谢反馈。目前用tab切换，全量渲染肯定还是存在一些问题的，我也在考虑要怎么改成动态渲染。
如果你有好的idea，可以提出来或者一起维护提 pr😉

**Comment by niyg** [comment]
二十个菜单的时候，卡的不行了，有救吗
