### ISSUE TITLE
代码里添加了路由后页面不显示当前添加的路由

### ISSUE THREAD

**Issue by Haiwar** [hsl947/react-antd-multi-tabs-admin#44]
#### Screenshot or Gif（截图或动态图）

![](https://camo.githubusercontent.com/d7072ab76d6669e7f5611566e36252db45b8eefc00182b68ec9ff122d6ad91ec/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30352f31302f74367350425655544f634771466e432e706e67)

![](https://camo.githubusercontent.com/6f554edf85351fe0a1c2303c3ac6c658294a29983d9623222ae32b6766c3bb22/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30352f31302f5741357673494d474656796e6633652e706e67)

#### Other relevant information（格外信息）
- Your OS:
- Your broswer version:

**Comment by Haiwar** [comment]
![微信图片_20220510154335 _1_.png](https://s2.loli.net/2022/05/10/WA5vsIMGFVynf3e.png)

![微信图片_20220510154301 _1_.png](https://s2.loli.net/2022/05/10/t6sPBVUTOcGqFnC.png)

**Comment by hsl947** [comment]
@Haiwar `role:list:add` 可能不在权限列表里，你可以查看登录后保存的 permission

**Comment by Haiwar** [comment]
![微信图片_20220511105039 _1_.png](https://s2.loli.net/2022/05/11/wSbA3LiYgN4ujFQ.png)

**Comment by hsl947** [comment]
@Haiwar 我排查了一下，是路由菜单顺序的问题。
你需要把`角色列表添加` 菜单 `角色列表` ，这个是权限控制时的路由层级匹配优先度。
大概意思就是说，路由层级需要渐进😉
