### ISSUE TITLE
在ant-design-pro 怎么使用，希望出一个小例子

### ISSUE THREAD

**Issue by yangbinsoft** [hsl947/react-antd-multi-tabs-admin#45]
## Feature request（新功能建议）

看到这个样式真的很棒，由于项目中用的是 ant-design-pro , 不知如何改造了，求大神指教

**Comment by hsl947** [comment]
不好意思，亲，咱们这套系统不是基于antd-pro开发的，集成的话，只能看你需要哪些功能，去搬对应的代码了。
顺便问一下，你指的是什么样式很棒？😂

**Comment by yangbinsoft** [comment]
好的，我已经抄袭好了到最新的ant-pro了，就是这个样式
![image](https://user-images.githubusercontent.com/15042338/168544418-43ecfd0f-40cc-4bbb-b8a3-b1dc287b0586.png)

**Comment by hsl947** [comment]
@yangbinsoft 非常棒哦！有任何想法建议可以提出来
