### ISSUE TITLE
lodash这个包异常

### ISSUE THREAD

**Issue by xu-Aurora** [hsl947/react-antd-multi-tabs-admin#47]
我没有安装这个包，为什么analyze包分析里面会存在打包了lodash这个库啊

**Comment by hsl947** [comment]
@xu-Aurora lodash
虽然你没安装，但是很多依赖包里都有引用的，你可以到 yarn.lock 里面一搜就知道了。
![image](https://user-images.githubusercontent.com/18359814/179351150-0f20ed7a-9ba7-43db-bc37-3df01acf99d9.png)
