### ISSUE TITLE
eslint配置的有问题

### ISSUE THREAD

**Issue by xu-Aurora** [hsl947/react-antd-multi-tabs-admin#49]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/35291465/171325579-8ccb7164-f782-450b-8be8-dab455b96a28.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/35291465/171325600-889bb211-9f04-40f0-82c6-490014788e76.png">

**Comment by hsl947** [comment]
eslint的问题，这个你可以自定义，不一定要用原有配置
