### ISSUE TITLE
tabPanes可以控制不缓存嘛？

### ISSUE THREAD

**Issue by xu-Aurora** [hsl947/react-antd-multi-tabs-admin#51]
我想达到的是点击左侧菜单栏进入页面不缓存，页面会重新获取请求。点击tabPanes菜单时，页面走缓存

**Comment by hsl947** [comment]
@xu-Aurora 你说的这个，现在就能实现。你可以在点击左侧菜单的时候去触发一个刷新页面的事件，就跟标签页上右击刷新一样的。
