### ISSUE TITLE
大佬  怎么关闭顶部的菜单  显示到左侧啊   不习惯顶部菜单

### ISSUE THREAD

**Issue by lhtuling** [hsl947/react-antd-multi-tabs-admin#71]
大佬  怎么关闭顶部的菜单  显示到左侧啊   不习惯顶部菜单

**Comment by theCword** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by hsl947** [comment]
> 大佬 怎么关闭顶部的菜单 显示到左侧啊 不习惯顶部菜单



> 大佬 怎么关闭顶部的菜单 显示到左侧啊 不习惯顶部菜单

![image](https://github.com/hsl947/react-antd-multi-tabs-admin/assets/18359814/381b2e52-b9d6-4be6-8f48-59d841b77c57)
这里修改布局

**Comment by lhtuling** [comment]
感谢大佬

**Comment by theCword** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
