### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by giserzhangwl** [hsl947/react-antd-multi-tabs-admin#9]
D:/Workspace/前端项目/base-react-ts-hooks/src/components/common/myUpload/index.tsx
TypeScript error in D:/Workspace/前端项目/base-react-ts-hooks/src/components/common/myUpload/index.tsx(65,6):
Type '{ children: Element; action: string; onStart: () => void; customRequest({ file, filename }: { file: any; filename: any; }): false | { abort(): void; }; className: string; listType: "picture-card"; showUploadList: false; }' is not assignable to type 'UploadProps<any>'.
  Types of property 'customRequest' are incompatible.
    Type '({ file, filename }: { file: any; filename: any; }) => false | { abort(): void; }' is not assignable to type '(options: UploadRequestOption<any>) => void'.
      Types of parameters '__0' and 'options' are incompatible.
        Type 'UploadRequestOption<any>' is not assignable to type '{ file: any; filename: any; }'.
          Property 'filename' is optional in type 'UploadRequestOption<any>' but required in type '{ file: any; filename: any; }'.  TS2322

    63 | 
    64 |   return (
  > 65 |     <Upload
       |      ^
    66 |       className="avatar-uploader"
    67 |       listType="picture-card"
    68 |       showUploadList={false}

**Comment by hsl947** [comment]
@giserzhangwl 请检查一下实际安装的 antd 的版本号是多少，是通过 yarn 安装依赖的吗

**Comment by hsl947** [comment]
@giserzhangwl 我建议你把antd的版本号固定 4.2.0，再重新安装依赖
`"antd": "^4.2.0"` -> `"antd": "4.2.0"`
